
version: '3'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8000:8000
  db:
    image: 'postgres:13.3'
    container_name: db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
      - app-data:/var/lib/postgresql/data
volumes:
  app-data: